### ISSUE TITLE
Support for Swift 4.2 (Xcode 10)

### ISSUE THREAD

**Issue by el-hoshino** [el-hoshino/NotAutoLayout#113]

**Comment by ajfigueroa** [comment]
I can help with this if you'd like ✋

**Comment by el-hoshino** [comment]
@ajfigueroa That's so kind of you 😆 Thank you so much!

**Comment by ajfigueroa** [comment]
When I build with the Xcode 10 (iOS 12 SDK) I get an error about Float no longer conforming to FloatingPoint: https://github.com/el-hoshino/NotAutoLayout/blob/b07a2928582eb7bca2c7f9b2baf8dd9f54563f14/NotAutoLayout/NotAutoLayout/Types/Float.swift#L127

I wonder what changed, I'll have to investigate.
