### ISSUE TITLE
Build on Xcode 13

### ISSUE THREAD

**Issue by ykws** [el-hoshino/NotAutoLayout#141]
Now build failed on Xcode 13 ~~Beta~~, because could not use `@available` in Enum cases.

Drop iOS 9 and 10, then can remove `@available`.
I think if limiting to support iOS 11 and above will a very small affect us only.
The following data is iOS Usage by Apple:

https://developer.apple.com/support/app-store/

<img width="357" alt="Screen Shot 2021-08-05 at 3 59 54" src="https://user-images.githubusercontent.com/5770480/128242884-10c6ba48-568f-47f9-8e83-05977162b497.png">

**Additional context**

### Environment
- Xcode: Version 13.0 beta 4 (13A233) / 13.0 (13A233)
- macOS: Big Sur 11.4 / 11.5.1

### Error Message

```
Enum cases with associated values cannot be marked potentially unavailable with '@available'
```

### Screenshots

<img width="771" alt="Screen Shot 2021-08-03 at 4 56 55" src="https://user-images.githubusercontent.com/5770480/128242867-2b327742-deea-49b2-9b05-68f01db6ad62.png">

### Developer Forums

[Enum cases with associated values cannot be marked potentially unavailable](https://developer.apple.com/forums/thread/682351)

**Comment by ykws** [comment]
@el-hoshino Thank you for merged #142 #144 
We want to specify version 4.0.0-beta for this issue.
Cloud you create pre-release version it?

For your reference, I tried it in my forked repository.
https://github.com/ykws/NotAutoLayout/releases/tag/v4.0.0-beta

If need to merge develop into the master, I will create a PR for it.

**Comment by ykws** [comment]
@el-hoshino We want to specify version 4.0.0 for this issue.
The reason of not beta release is fixed the following specification on Xcode13.

> The compiler used to erroneously accept @available annotations on enum cases with associated values that were newer than the deployment target. (80238318)
>
> While this worked in some cases, there was no way for the Swift runtime to perform the requisite dynamic layout needed in general, so this could cause crashes at runtime. The compiler now rejects such availability newer than the deployment target on enum cases.
>
> https://developer.apple.com/documentation/xcode-release-notes/xcode-13-release-notes

**Comment by el-hoshino** [comment]
@ykws please check it:
https://github.com/el-hoshino/NotAutoLayout/releases/tag/v4.0.0-alpha1
